### ISSUE TITLE
It's empty...

### ISSUE THREAD

**Issue by Manerr** [Crysicia/Crysicia#1]
Hey, maybe you didn't notice that, but your own readme.md (displayed in your profile page) is really empty.
It seems to need some work, you can add your skills or your projects , markdown is really easy-to-use.
I'll make a fork if you're lazy to work on ;)

**And don't forget emails I've sent to you...**

P.S : It's one issue, not a ping. xD

**Comment by Crysicia** [comment]
Hi @Paul-Thorel,
Thanks for this report!
I am aware of the fact that this repository feels a little... empty, I'll work on it during the following days / months.

Also, I didn't forget your email, I'm currently overwhelmed by work ^^'.
I'll reach out to you soon ;)

Thanks again and talk to you soon!

**Comment by Manerr** [comment]
> Hi @Paul-Thorel,
> Thanks for this report!
> I am aware of the fact that this repository feels a little... empty, I'll work on it during the following days / months.
> 
> Also, I didn't forget your email, I'm currently overwhelmed by work ^^'.
> I'll reach out to you soon ;)
> 
> Thanks again and talk to you soon!

You don't have to apologize, it's totally normal (forget my French) , and I remember I've making same few months ago (wip to forgotten repo) 

Okay, let's close this issue(because it doesn't matter anymore : you're "fixing" it.)
Have a nice day, and yeah, talk you soon :')
